/* eslint-disable */
require('./apps')
require('./create')
require('./down')
require('./hamburger')
require('./history')
require('./home')
require('./library')
require('./liked')
require('./notification')
require('./search')
require('./subscriptions')
require('./trending')
require('./watch')
require('./yourvideos')
